version: '3.4'

services:
  timesheetdb:
    container_name: timesheetdb
    environment:
        SA_PASSWORD: "123jaja123"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1435:1433"

  timesheet.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=timesheetdb;Database=TimeSheet.Api;User Id=sa;Password=123jaja123" 
    depends_on: 
      - timesheetdb
    ports:
      - "8000:80"